repos:
- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
    - id: isort
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.2
  hooks:
    - id: ruff-check
      args: [ --fix ]
    - id: ruff-format